### ISSUE TITLE
SLCT, error cython

### ISSUE THREAD

**Issue by AEnguerrand** [logpai/logparser#12]
Hi,
I try to use SLCT demo with the docker image of project, but the symbol _Py_ZeroStruct_ was not defined inside a library _SLCT_ in Git :

```bash
root@b63e6065c724:/logparser/logparser/SLCT/demo/SLCT_demo_BGL# python precision_10_times.py 
Traceback (most recent call last):
  File "precision_10_times.py", line 6, in <module>
    from SLCT_complete import *
  File "/logparser/logparser/SLCT/demo/SLCT_demo_BGL/SLCT_complete.py", line 5, in <module>
    from logparser import slct
ImportError: ../../logparser/slct.so: undefined symbol: _Py_ZeroStruct
```

For solve this problem, i have try to recompile this library (after i have fix import), but another problem:

```bash
root@b63e6065c724:/logparser/logparser/SLCT# python3 setup.py 
Building extenstion modules...
==============================================
logparser/slct/slct.pyx: cannot find cimported module '.cslct'
Compiling logparser/slct/slct.pyx because it changed.
[1/1] Cythonizing logparser/slct/slct.pyx

Error compiling Cython file:
------------------------------------------------------------
...
from cpython.string cimport PyString_AsString
from libc.stdlib cimport *
from .cslct cimport *
^
------------------------------------------------------------

logparser/slct/slct.pyx:3:0: relative cimport beyond main package is not allowed

Error compiling Cython file:
------------------------------------------------------------
...
    length = len(content)
    cdef int c_argc = <int> length

    cdef char ** c_argv = to_cstring_array(content)

    mainFunction(c_argc, c_argv)  #invoke the original C function
   ^
------------------------------------------------------------

logparser/slct/slct.pyx:22:4: undeclared name not builtin: mainFunction

Error compiling Cython file:
------------------------------------------------------------
...
    length = len(content)
    cdef int c_argc = <int> length

    cdef char ** c_argv = to_cstring_array(content)

    mainFunction(c_argc, c_argv)  #invoke the original C function
                        ^
------------------------------------------------------------

logparser/slct/slct.pyx:22:25: Cannot convert 'char **' to Python object
Traceback (most recent call last):
  File "setup.py", line 20, in <module>
    ext_modules = cythonize(ext_modules)
  File "/root/anaconda3/lib/python3.6/site-packages/Cython/Build/Dependencies.py", line 1039, in cythonize
    cythonize_one(*args)
  File "/root/anaconda3/lib/python3.6/site-packages/Cython/Build/Dependencies.py", line 1161, in cythonize_one
    raise CompileError(None, pyx_file)
Cython.Compiler.Errors.CompileError: logparser/slct/slct.pyx
```

How to use _SLCT_ demo? What is the process to compile and run? 

Thank you in advance

**Comment by jimzhu** [comment]
Please follow our new version at dev branch. The docs are sync with dev.
