### ISSUE TITLE
Inquire how to avoid "Error: need to escape, but no escapechar set" this problem

### ISSUE THREAD

**Issue by Tan3364** [logpai/logparser#122]
Hi, when I tried to use whole raw logfile datasets to the parser, I used the Drain, then it showed this bug. 
I wanted to ask if I need to do anything before putting it in the Drain.
But I tried any given 2k datasets, it will not show this bug.
Traceback (most recent call last):
  File "C:\Users\Lenovo\Desktop\logparser-main\logparser-main\logparser\Drain\Try.py", line 56, in <module>
    parser.parse(log_file)
  File "C:\Users\Lenovo\.conda\envs\GLBench\lib\site-packages\logparser\Drain\Drain.py", line 312, in parse
    self.outputResult(logCluL)
  File "C:\Users\Lenovo\.conda\envs\GLBench\lib\site-packages\logparser\Drain\Drain.py", line 237, in outputResult
    self.df_log.to_csv(
  File "C:\Users\Lenovo\AppData\Roaming\Python\Python310\site-packages\pandas\core\generic.py", line 3772, in to_csv
    return DataFrameRenderer(formatter).to_csv(
  File "C:\Users\Lenovo\AppData\Roaming\Python\Python310\site-packages\pandas\io\formats\format.py", line 1186, in to_csv
    csv_formatter.save()
  File "C:\Users\Lenovo\AppData\Roaming\Python\Python310\site-packages\pandas\io\formats\csvs.py", line 259, in save
    self._save()
  File "C:\Users\Lenovo\AppData\Roaming\Python\Python310\site-packages\pandas\io\formats\csvs.py", line 264, in _save
    self._save_body()
  File "C:\Users\Lenovo\AppData\Roaming\Python\Python310\site-packages\pandas\io\formats\csvs.py", line 302, in _save_body
    self._save_chunk(start_i, end_i)
  File "C:\Users\Lenovo\AppData\Roaming\Python\Python310\site-packages\pandas\io\formats\csvs.py", line 313, in _save_chunk
    libwriters.write_csv_rows(
  _File "pandas\_libs\writers.pyx", line 72, in pandas._libs.writers.write_csv_rows
_csv.Error: need to escape, but no escapechar set_

Process finished with exit code 1

**Comment by sebm123** [comment]
```c++
****
```

**Comment by Tan3364** [comment]
> ```c++
> ****
> ```

Hi, could you tell me the exact processing?
