### ISSUE TITLE
Run LogParser-Error

### ISSUE THREAD

**Issue by zraiss** [logpai/logparser#71]
Hello All,

I have this error (I use Python3)
Traceback (most recent call last):
  File "Drain_demo.py", line 20, in <module>
    parser.parse(log_file)
  File "/logparser/demo/../logparser/Drain/Drain.py", line 283, in parse
    os.makedirs(self.savePath)
  File "/usr/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: 'Drain_result/'

**Comment by PinjiaHe** [comment]
not sure what might be the root cause on your computer. maybe you could check this out: https://stackoverflow.com/questions/36434764/permissionerror-errno-13-permission-denied
